apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: servicio-api-kaic-datapath
spec:
  template:
    spec:
      containers:
        - image: us-central1-docker.pkg.dev/datapath-deploy-api-v1/repo-servicio-prediccion-datapath/image-v1-servicio-prediccion-datapath:latest
          env:
          ports:
            - containerPort: 4001